source: .
encoding: utf-8
highlighter: rouge
safe: true
lsi: false
baseurl: /shibboleth-idp-installer

kramdown:
  input: GFM

markdown: kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
