---
- hosts: idp-servers
  vars:
    software:
      shib_idp:
        version: 3.1.2
    installer:
      root: /opt/shibboleth-idp-installer
      path: /opt/shibboleth-idp-installer/build
    jetty:
      version: 9.2.10.v20150310
      sha256sum: 0034587a3dcfdab23fca28291e5e22ae7ff6e80f9f4c7a67f5b2b7777a84b40e
      root: /opt/jetty
      home: /opt/jetty/jetty-distribution-9.2.10.v20150310
      base: /opt/shibboleth/jetty
      current: /opt/jetty/current
      state_directory: /tmp/jetty
      dta_ssl:
        version: 1.0.0
    shib_idp:
      version: "{{ software.shib_idp.version }}"
      sha256sum: 2519918257f77a80816de3bdb56b940a9f59325b6aa550aad53800291c1dec04
      home_root: /opt/shibboleth/shibboleth-idp
      home: /opt/shibboleth/shibboleth-idp/shibboleth-idp-{{ software.shib_idp.version }}
      src_root: /opt/shibboleth/shibboleth-src
      src: /opt/shibboleth/shibboleth-src/shibboleth-identity-provider-{{ software.shib_idp.version }}
      keystore_password: "{{ lookup('password', 'passwords/' + inventory_hostname + '/shib_idp_keystore chars=letters,digits length=64') }}"
      cookie_enc_key_password: "{{ lookup('password', 'passwords/' + inventory_hostname + '/cookie_enc_key chars=letters,digits length=64') }}"
      aepst_salt: "{{ lookup('password', 'passwords/' + inventory_hostname + '/aespt_salt chars=letters,digits length=64') }}"
      targeted_id_salt: "{{ lookup('password', 'passwords/' + inventory_hostname + '/targeted_id_salt chars=letters,digits length=64') }}"
    db:
      name: idp_db
      username: idp_admin
      password: "{{ lookup('password', 'passwords/' + inventory_hostname + '/mariadb chars=letters,digits length=64') }}"
      mysql_connector:
        version: 5.1.35
        sha256sum: fa77909a62363c1aa49ef5ab537ed4affe90a4a6aa5dd1045555b16b2611306d
    aaf_shib_ext:
      version: 1.0.0

  tasks:
    - name: 'Create required directories for installer setup'
      file:
        name: '{{ item }}'
        state: directory
        owner: root
        group: root
        mode: 0700
      with_items:
        - '{{ installer.root }}'
        - '{{ installer.path }}'

    - name: 'Update yum packages (yum -y update)'
      yum: name=* state=latest

    - name: 'Disable SELinux'
      selinux:
        policy: targeted
        state: disabled

    - name: 'Install required packages'
      yum: pkg={{ item }} state=installed
      with_items:
        - httpd
        - mod_ssl
        - mod_ldap
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
        - mariadb-server
        - mariadb-devel
        - mariadb
        - MySQL-python
        - ntp
        - expect

    - name: 'Enable NTP service'
      service: name=ntpd state=started enabled=yes

    - include: tasks/jetty.yml
    - include: tasks/db.yml
    - include: tasks/idp.yml
    - include: tasks/apache.yml
    - include: tasks/firewalld.yml

  handlers:
    - name: Restart idp
      service:
        name: idp
        state: restarted
    - name: Restart Apache
      service:
        name: httpd
        state: restarted

