---
- hosts: idp-servers
  vars:
    aaf_binaries:
      baseurl: https://aaf-binaries.s3-ap-southeast-2.amazonaws.com 
    download:
      jetty:
        baseurl: "{{ aaf_binaries.baseurl }}/jetty"
        version: 9.3.5.v20151012
        sha256sum: 24e80e350fcc9749aa4a29913c34917ad238a0fa3abdb7d7c9b42dc40bdf0f9b
        url: "{{ download.jetty.baseurl }}/jetty-distribution-{{ download.jetty.version }}.tar.gz"
    software:
      shib_idp:
        baseurl: "{{ aaf_binaries.baseurl }}/shibboleth"
        version: 3.2.0
        sha256sum: 302c45a4e0814e97a1c01950137d328e0a8630638b35bdd6ae50af9510bcea84
      mysql_connector:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/Connector-J"
        version: 5.1.35
        sha256sum: fa77909a62363c1aa49ef5ab537ed4affe90a4a6aa5dd1045555b16b2611306d
      dta_ssl:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/jetty9-dta-ssl"
        version: 1.0.0
        sha256sum: 9c62a5999d5adddea905d7caf4220fc073e6033b755f224084cc240dc8d992a6
      commons_dbcp2:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/commons_dbcp2"
        version: 2.1.1
        sha256sum: d6181397b20490aa9b3a793a19c2b75f31af032040d976db1cd97cc2f0ef4379
      commons_pool2:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/commons_pool2"
        version: 2.4.2
        sha256sum: 175ddacc9364b4619ac0fd0fd22acc9d4c372f9099ae5208e8cb72e04a9a872e
      aaf_shib_ext:
        baseurl: "{{ aaf_binaries.baseurl }}/jars/aaf_shib_ext"
        version: 1.0.1
        sha256sum: 854314b1b8438ec993df71fe745f375f637dbc2ddd86f8cd5010d01dea6b5aa3

    installer:
      root: /opt/shibboleth-idp-installer
      path: /opt/shibboleth-idp-installer/build
      repository: /opt/shibboleth-idp-installer/repository
    jetty:
      root: /opt/jetty
      home: /opt/jetty/jetty-distribution-{{ download.jetty.version }}
      base: /opt/shibboleth/jetty
      current: /opt/jetty/current
      state_directory: /tmp/jetty
      dta_ssl:
        version: '{{ software.dta_ssl.version }}'
        sha256sum: '{{ software.dta_ssl.sha256sum }}'
        url: "{{ software.dta_ssl.baseurl }}/jetty9-dta-ssl-{{software.dta_ssl.version}}.jar"
    shib_idp:
      version: "{{ software.shib_idp.version }}"
      sha256sum: "{{ software.shib_idp.sha256sum }}"
      url: "{{ software.shib_idp.baseurl }}/shibboleth-identity-provider-{{ software.shib_idp.version }}.tar.gz"
      home_root: /opt/shibboleth/shibboleth-idp
      home: /opt/shibboleth/shibboleth-idp/shibboleth-idp-{{ software.shib_idp.version }}
      src_root: /opt/shibboleth/shibboleth-src
      src: /opt/shibboleth/shibboleth-src/shibboleth-identity-provider-{{ software.shib_idp.version }}
      keystore_password: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/shib_idp_keystore chars=letters,digits length=64') }}"
      cookie_enc_key_password: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/cookie_enc_key chars=letters,digits length=64') }}"
      aepst_salt: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/aespt_salt chars=letters,digits length=64') }}"
      targeted_id_salt: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/targeted_id_salt chars=letters,digits length=64') }}"
    db:
      name: idp_db
      username: idp_admin
      password: "{{ lookup('password', installer.repository + '/passwords/' + inventory_hostname + '/mariadb chars=letters,digits length=64') }}"
      mysql_connector:
        version: "{{ software.mysql_connector.version }}"
        url: "{{ software.mysql_connector.baseurl }}/mysql-connector-java-{{ software.mysql_connector.version }}.tar.gz"
    aaf_shib_ext:
      version: "{{ software.aaf_shib_ext.version }}"
      sha256sum: "{{software.aaf_shib_ext.sha256sum }}"
      url : "{{ software.aaf_shib_ext.baseurl }}/aaf-shib-ext-{{ software.aaf_shib_ext.version }}.jar"
    additional_jars:
      commons_dbcp2:
        version: "{{ software.commons_dbcp2.version }}"
        sha256sum: "{{software.commons_dbcp2.sha256sum }}"
        url: "{{software.commons_dbcp2.baseurl }}/commons-dbcp2-{{ software.commons_dbcp2.version }}-bin.tar.gz"
      commons_pool2:
        version: "{{software.commons_pool2.version }}"
        sha256sum: "{{software.commons_pool2.sha256sum }}"
        url: "{{software.commons_pool2.baseurl }}/commons-pool2-{{ software.commons_pool2.version }}-bin.tar.gz"
  tasks:
    - name: 'Create required directories for installer setup'
      file:
        name: '{{ item }}'
        state: directory
        owner: root
        group: root
        mode: 0700
      with_items:
        - '{{ installer.root }}'
        - '{{ installer.path }}'

    - name: 'Update yum packages (yum -y update)'
      yum: name=* state=latest

    - name: 'Disable SELinux'
      selinux:
        policy: targeted
        state: disabled

    - name: 'Install required packages'
      yum: pkg={{ item }} state=installed
      with_items:
        - httpd
        - mod_ssl
        - mod_ldap
        - java-1.8.0-openjdk
        - java-1.8.0-openjdk-devel
        - mariadb-server
        - mariadb-devel
        - mariadb
        - MySQL-python
        - ntp
        - expect

    - name: 'Enable NTP service'
      service: name=ntpd state=started enabled=yes

    - include: tasks/jetty.yml
    - include: tasks/db.yml
    - include: tasks/idp.yml
    - include: tasks/apache.yml
    - include: tasks/firewalld.yml

  handlers:
    - name: Restart idp
      service:
        name: idp
        state: restarted
    - name: Restart Apache
      service:
        name: httpd
        state: restarted

