---
- hosts: idp-servers
  vars:
    installer:
      root: /opt/shibboleth-idp-installer
      path: /opt/shibboleth-idp-installer/build
      repository: /opt/shibboleth-idp-installer/repository

  tasks:
    - name: 'Copy example files to assets only if they do not exist'
      copy:
        src: '{{ installer.repository }}/assets/idp.example.edu.dist/'
        dest: '{{ installer.repository }}/assets/{{inventory_hostname}}'
        force: no
