source: .
encoding: utf-8
highlighter: pygments
safe: true
lsi: false
baseurl: /shibboleth-idp-installer

kramdown:
  input: GFM

markdown: redcarpet
redcarpet:
    extensions: [with_toc_data, tables]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "upgrade"
