---
- name: 'Restore IdP 3.x credentials'
  copy:
    src: 'assets/{{ inventory_hostname }}/idp/credentials/{{ item }}'
    dest: '{{ shib_idp.home }}/credentials'
    owner: root
    group: root
    mode: 600
  with_items:
  - credentials/idp-backchannel.crt
  - credentials/idp-backchannel.p12
  - credentials/idp-encryption.crt
  - credentials/idp-encryption.key
  - credentials/idp-signing.crt
  - credentials/idp-signing.key
  - credentials/idp-backchannel.p12
  - credentials/sealer.jks
  - credentials/sealer.kver
