---
- stat:
    path: 'assets/{{inventory_hostname}}/idp/credentials/sealer.jks'
  register: sealer_keystore_file

- name: 'Restore IdP 3.x credentials'
  copy:
    src: 'assets/{{inventory_hostname}}/idp/credentials/{{ item }}'
    dest: '{{ shib_idp.home }}/credentials'
    owner: root
    group: root
    mode: 600
  with_items:
  - credentials/idp-backchannel.crt
  - credentials/idp-backchannel.p12
  - credentials/idp-encryption.crt
  - credentials/idp-encryption.key
  - credentials/idp-signing.crt
  - credentials/idp-signing.key
  - credentials/idp-backchannel.p12
  - credentials/sealer.jks
  - credentials/sealer.kver
  when: sealer_keystore_file.stat.exists

- name: 'Fix IdP 3.x credential permissions'
  file:
    name: '{{ shib_idp.home }}/{{ item }}'
    owner: root
    group: jetty
    mode: 0640
  with_items:
  - credentials/idp-encryption.key
  - credentials/idp-signing.key
  - credentials/idp-backchannel.p12
  when: sealer_keystore_file.stat.exists

- name: 'Restore IdP 2.x credentials'
  copy:
    src: 'assets/{{inventory_hostname}}/idp/credentials/{{ item }}'
    dest: '{{ shib_idp.home }}/credentials'
    owner: root
    group: root
    mode: 600
  with_items:
  - credentials/idp.crt
  - credentials/idp.key
  - credentials/idp.jks
  - credentials/idp.p12
  when: not sealer_keystore_file.stat.exists

- name: 'Fix IdP 2.x credential permissions'
  file:
    name: '{{ shib_idp.home }}/{{ item }}'
    owner: root
    group: jetty
    mode: 0640
  with_items:
  - credentials/idp.crt
  - credentials/idp.jks
  - credentials/idp.p12
  when: not sealer_keystore_file.stat.exists
