---
- name: 'Restore IdP 3.x credentials'
  copy:
    src: 'assets/{{ inventory_hostname }}/idp/credentials/{{ item }}'
    dest: '{{ shib_idp.home }}/credentials'
    owner: root
    group: root
    mode: 0644
  with_items:
  - idp-backchannel.crt
  - idp-backchannel.p12
  - idp-encryption.crt
  - idp-encryption.key
  - idp-signing.crt
  - idp-signing.key
  - idp-backchannel.p12
  - sealer.jks
  - sealer.kver

- name: 'Ensure correct credentials for certs'
  file:
    name: '{{ shib_idp.home }}/credentials/{{ item }}'
    owner: root
    group: root
    mode: 0644
  with_items:
  - federation-metadata-cert.pem
  - idp-backchannel.crt
  - idp-encryption.key
  - idp-signing.key
  - sealer.jks
  - sealer.kver

- name: 'Ensure correct credentials for keys'
  file:
    name: '{{ shib_idp.home }}/credentials/{{ item }}'
    owner: root
    group: jetty
    mode: 0640
  with_items:
  - idp-backchannel.p12
  - idp-encryption.key
  - idp-signing.key
