---
- name: 'Restore IdP 3.x credentials'
  copy:
    src: 'assets/{{ inventory_hostname }}/idp/credentials/{{ item }}'
    dest: '{{ shib_idp.home }}/credentials'
    owner: root
    group: root
    mode: 0600
  with_items:
  - idp-backchannel.crt
  - idp-backchannel.p12
  - idp-encryption.crt
  - idp-encryption.key
  - idp-signing.crt
  - idp-signing.key
  - idp-backchannel.p12
  - sealer.jks
  - sealer.kver
