---
- name: 'Enable iptables'
  service: name=iptables state=started enabled=yes

- name: 'Open Apache firewall ports'
  command: lokkit --service=https
  changed_when: false

- name: 'Open IdP Backchannel port'
  command: lokkit --port=8443:tcp
  changed_when: false
